backend:
    name: github
    branch: main # change this to your branch
    repo: chark1es/gdpt-anoma # change this to your repo
    site_domain: chuavanhanh.org # change this to your domain
    base_url: https://chuavanhanh.org # change this to your prod URL
    auth_endpoint: oauth # the oauth route provided by the integration
